version: '2'
config:
  slack_notify: true
  slack_channel: pelias-ci-cd
environment:
  GOCACHE: /tmp/.cache/go-build
jobs:
  build_docker:
    steps:
      - build_image:
          dockerfile: ./Dockerfile
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: operations
          workload: pelias-api
          spinnaker_pipeline: generic-v2
          deployment_config: dev
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-operations-prod
          namespace: delivery
          workload: pelias-api
          spinnaker_pipeline: generic-v2
          deployment_config: prod
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - develop
                - master
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - master
deployment_config:
  dev:
    ingress:
      hosts:
        - host: pelias-placeholder.dev.tiki.services
          paths:
            - path: /
              port: '3000'
    replicaCount: 1
    envVars:
      PELIAS_CONFIG: ./pelias.json
    volumes:
      - name: pelias-placeholder-poneglyph
        persistentVolumeClaim:
          claimName: pelias-placeholder
    volumeMounts:
      - mountPath: /data/placeholder
        name: pelias-placeholder-poneglyph
  prod:
    ingress:
      hosts:
        - host: pelias-placeholder.tiki.services
          paths:
            - path: /
              port: '3000'
    replicaCount: 1
    envVars:
      PELIAS_CONFIG: ./pelias.json
    volumes:
      - name: pelias-placeholder-poneglyph
        persistentVolumeClaim:
          claimName: pelias-placeholder
    volumeMounts:
      - mountPath: /data/placeholder
        name: pelias-placeholder-poneglyph
